### ISSUE TITLE
✨Voice visualizator module

### ISSUE THREAD

**Issue by Shinnken** [Med0kin/BETA-Humanoid-robot#9]
Something that will work as speaking expression for robot.

**Comment by terminator765** [comment]
**### 30.04.2023**
_Basic visualizer from yt channel works, however only with microphone as an input._

**Pros:**
_Looks quite nice._

**Cons:**
_Uses matplotlib library._

**###31.04.2023**
_I can change colour and style of the line._

**###01.04.2023**
_Code written by AI works with files as an input, but still using matplotlib._
**Goals:**
_-Get rid of matplotlib
-Put the visualization to the PySide._
**Thing to check -**_PyQtGraph library._

**Comment by terminator765** [comment]
###07.04.2023
_I copied code from pyqt site to show "updating plot" and modified it to work with data from mic (pyaudio), however data format is not compatible._
**Goal:**
-Change data format.

**Comment by terminator765** [comment]
###08.04.2023
_I managed to change data format from tuple to NDarray and plot it in real time but the plot doesn't look as it supposed to look._
**Goal:**
- Make the plot look like waveform and not like stripes.

**Comment by terminator765** [comment]
###8.04.2023
_Success!!! I managed to visualize the sound from the **wav.** file. Visualization is a bit too slow but it works._

**Comment by terminator765** [comment]
###4.05.2023
**Goal:**

- Display a background image for the visualizer.
